openapi: "3.0.0"
info:
  version: v3
  title: crypto-currency market summary API.
  contact:
    name: Danush Kumar
    email: danushk97@gmail.com

servers:
- url: /v3
  description: Development server

paths:
  /health-check:
    get:
      operationId: src.controller.health.health_check
      tags:
      - Health Check
      summary: Ensures the application's health
      responses:
        200:
          description: Application is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: up
  /crypto/markets/summaries:
    get:
      operationId: src.controller.crypto_market_summary.retrieve_all
      tags:
      - Crypto Market Summaries
      summary: Get all available crypto-currency market summaries
      responses:
        200:
          description: Successful retrieve operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/crypto_market_summary"
  /crypto/markets/{market}/summary:
    get:
      operationId: src.controller.crypto_market_summary.retrieve_market_summary_for
      tags:
      - Crypto Market Summaries
      summary: Get crypto-currency market summary for market
      parameters:
        - in: path
          name: market
          schema:
            type: string
          required: true
          description: A crypto-currency market name.
      responses:
        200:
          description: Successful retrieve operation
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/crypto_market_summary"

components:
  schemas:
    crypto_market_summary:
      type: object
      properties:
        symbol:
          type: string
        high:
          type: string
        low:
          type: string
        volume:
          type: string
        quote_volume:
          type: string
        percent_change:
          type: string
        updated_at:
          type: string
